### ISSUE TITLE
Storing passwords in cleartext

### ISSUE THREAD

**Issue by itzrahulsoni** [nareshv/secure-conf#5]
I would recommend against developers keeping the configuration secrets in a config file. They can use https://www.npmjs.com/package/masterkey to store the secrets in a secure place like Azure Key-Vault!

**Comment by nareshv** [comment]
Not sure whats your intent of creating this ticket. This library already supports encryption of config files instead of storing them in plain-text. 

Your library `masterkey` can be helpful for Azure users. Not all users have Azure access, thereby limiting the usability of the library.

**Comment by itzrahulsoni** [comment]
Thanks for the quick revert @nareshv. I created this issue since I wanted to request you to link this repo to the masterkey project for folks who have Azure access.
